"""
Django settings for doodle_server project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from os import getenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4zxrw^8b9@5jlq3+%k+sv_p_(l#zz+#t63j$xwlsac3$v2p4zn"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv("DJANGO_DEBUG", False)

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",
    # "django.contrib.auth",
    # "django.contrib.contenttypes",
    # "django.contrib.sessions",
    # "django.contrib.messages",
    # "django.contrib.staticfiles",
    "corsheaders",

    "doodle",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # "django.contrib.sessions.middleware.SessionMiddleware",
    # "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    # "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "django.contrib.messages.middleware.MessageMiddleware",
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "doodle_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            # "context_processors": [
            #     "django.template.context_processors.debug",
            #     "django.template.context_processors.request",
            #     "django.contrib.auth.context_processors.auth",
            #     "django.contrib.messages.context_processors.messages",
            # ],
        },
    },
]

WSGI_APPLICATION = "doodle_server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if getenv('SQLITE_DB', 'false') == 'true':
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': getenv('POSTGRES_NAME', 'app'),
            'USER': getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': getenv('POSTGRES_HOST', 'db'),
            'PORT': getenv('POSTGRES_PORT', '5432'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "https://example.com",
# ]
#
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:8000'
# ],
# ALLOWED_HOSTS = [
#     'localhost',
# ],
# CORS_ORIGIN_WHITELIST = [
#     'http://localhost:8000',
# ]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


DEFAULT_DOODLE_TEXT = """price -> float 
ProductId -> UUID 
StoreId -> UUID
date -> string


category -> Enum(
  "pantry",
  "household_supplies",
  "personal_care",
  "drinks"
)

Store -> {
  "id": StoreId,
  "name": string
}
  
ProductStoreAvailability -> {
  "store_id": StoreId,
  "count": int
}

Product -> {
  "id": ProductId,
  "name": string,
  "price": price,
  "expiration_date": date,
  "category": category,
  "availability": list[ProductStoreAvailability]
}
"""