// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%dOYQPOOO_QPO'#C`OOQO'#C_'#C_QYQPOOOdQPO,58zOOQO,58y,58yOOQO'#Cd'#CdO!_QPO'#CcO!sQPO'#CpO!xQPO'#CxO!}QPO'#DOOOQO'#Cc'#CcOOQO1G.f1G.fO#SQPO,59YO#XQPO'#CtOOQO'#Cs'#CsO#^QPO'#CrO#fQPO,59[O#kQPO,59dOdQPO,59jOOQO1G.t1G.tOdQPO,59`O!sQPO,59_OOQO1G.v1G.vOOQO'#C|'#C|OOQO'#C{'#C{O#pQPO1G/OO#xQPO1G/UOOQO1G.z1G.zOOQO1G.y1G.yO#kQPO,59gOOQO7+$j7+$jOOQO7+$p7+$pOOQO1G/R1G/R",
  stateData: "$]~OPOSxOS~OTPO~OUSO~OTVOXUOYUOZUO[UO]UO^ZO_ZO`ZOaZOeWOmXOsYO~Oc]OTVXvVXuVXjVXkVX~O^^O~OnbO~OtcO~OTdO~OieO~OjfOkfX~OkgO~O^hO~OjnOqoO~OupO~Osa`_mXYZ[]^TY~",
  goto: "!rsPPPtwPP}!WPPPPPPPPP!WP!WP!]!`!cPPP!WPP!i!lP!WRROQQORTRQ[SQkcRleVZSceRaWR`WQ_WRmfRjbQibRqn",
  nodeNames: "⚠ Comment JSL TypedefList TypeDef Identifier ARROW TypeExpr Primitive Int Float Fak Bool UUID FAKLITERAL IntLiteral FloatLiteral BoolLiteral UnionExpr PIPE SchemaExpr L_BRACE InnerSchemaExpr KeyValList KeyVal COLON COMMA R_BRACE EnumExpr Enum L_PAREN EnumValuesList EnumValue R_PAREN ListExpr List L_BRACKET R_BRACKET",
  maxTerm: 40,
  skippedNodes: [0,1],
  repeatNodeCount: 0,
  tokenData: "6U~RsXY#`YZ#`]^#`pq#`rs#qxy$fyz$k|}$p}!O$u!P!Q%Q!Q![%o![!]&Y!c!g&_!g!h&m!h!w&_!w!x(]!x!}&_!}#O){#P#Q*Q#R#S&_#T#U&_#U#V*V#V#Y&_#Y#Z+u#Z#]&_#]#^/i#^#`&_#`#a0s#a#g&_#g#h2c#h#i4{#i#o&_#o#p5u#p#q5z#q#r6P~#eSx~XY#`YZ#`]^#`pq#`~#tVOr#qrs$Zs#O#q#O#P#q#P;'S#q;'S;=`$`<%lO#q~$`O^~~$cP;=`<%l#q~$kOn~~$pOq~~$uOj~~$xP!`!a${~%QOU~~%TP!P!Q%W~%]SP~OY%WZ;'S%W;'S;=`%i<%lO%W~%lP;=`<%l%W~%tQ_~!O!P%z!Q![%o~%}P!Q![&Q~&VP`~!Q![&Q~&_Oi~~&dRT~!c!}&_#R#S&_#T#o&_~&rTT~!c!}&_#R#S&_#T#b&_#b#c'R#c#o&_~'WTT~!c!}&_#R#S&_#T#i&_#i#j'g#j#o&_~'lTT~!c!}&_#R#S&_#T#a&_#a#b'{#b#o&_~(SRm~T~!c!}&_#R#S&_#T#o&_~(bTT~!c!w&_!w!x(q!x!}&_#R#S&_#T#o&_~(vTT~!c!k&_!k!l)V!l!}&_#R#S&_#T#o&_~)[TT~!c!f&_!f!g)k!g!}&_#R#S&_#T#o&_~)rR]~T~!c!}&_#R#S&_#T#o&_~*QOt~~*VOu~~*[TT~!c!}&_#R#S&_#T#c&_#c#d*k#d#o&_~*pTT~!c!}&_#R#S&_#T#c&_#c#d+P#d#o&_~+UTT~!c!}&_#R#S&_#T#`&_#`#a+e#a#o&_~+lR[~T~!c!}&_#R#S&_#T#o&_~+zUT~!c!}&_#R#S&_#T#U,^#U#`&_#`#a-|#a#o&_~,cTT~!c!}&_#R#S&_#T#`&_#`#a,r#a#o&_~,wTT~!c!}&_#R#S&_#T#g&_#g#h-W#h#o&_~-]TT~!c!}&_#R#S&_#T#X&_#X#Y-l#Y#o&_~-sRa~T~!c!}&_#R#S&_#T#o&_~.RTT~!c!}&_#R#S&_#T#c&_#c#d.b#d#o&_~.gST~!c!}&_#R#S&_#T#U.s#U#o&_~.xTT~!c!}&_#R#S&_#T#h&_#h#i/X#i#o&_~/`RY~T~!c!}&_#R#S&_#T#o&_~/nTT~!c!}&_#R#S&_#T#b&_#b#c/}#c#o&_~0STT~!c!}&_#R#S&_#T#h&_#h#i0c#i#o&_~0jRX~T~!c!}&_#R#S&_#T#o&_~0xTT~!c!}&_#R#S&_#T#]&_#]#^1X#^#o&_~1^TT~!c!}&_#R#S&_#T#g&_#g#h1m#h#o&_~1rTT~!c!}&_#R#S&_#T#h&_#h#i2R#i#o&_~2YRs~T~!c!}&_#R#S&_#T#o&_~2hTT~!c!}&_#R#S&_#T#h&_#h#i2w#i#o&_~2|TT~!c!}&_#R#S&_#T#f&_#f#g3]#g#o&_~3bTT~!c!}&_#R#S&_#T#]&_#]#^3q#^#o&_~3vTT~!c!}&_#R#S&_#T#b&_#b#c4V#c#o&_~4[TT~!c!}&_#R#S&_#T#Z&_#Z#[4k#[#o&_~4rRZ~T~!c!}&_#R#S&_#T#o&_~5QTT~!c!}&_#R#S&_#T#f&_#f#g5a#g#o&_~5fTT~!c!}&_#R#S&_#T#i&_#i#j-W#j#o&_~5zOe~~6POc~~6UOk~",
  tokenizers: [0],
  topRules: {"JSL":[0,2]},
  tokenPrec: 137
})

