// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$zOYQPOOO_QPO'#C`OOQO'#C_'#C_QYQPOOOdQPO,58zOOQO,58y,58yOOQO'#Cd'#CdO![QPO'#CcO!mQPO'#CpO!rQPO'#CxOOQO'#Cc'#CcOOQO1G.f1G.fO!wQPO,59YO!|QPO'#CtOOQO'#Cs'#CsO#RQPO'#CrO#ZQPO,59[O#`QPO,59dOOQO1G.t1G.tOdQPO,59`O!mQPO,59_OOQO1G.v1G.vOOQO'#C|'#C|OOQO'#C{'#C{O#eQPO1G/OOOQO1G.z1G.zOOQO1G.y1G.yO#`QPO,59gOOQO7+$j7+$jOOQO1G/R1G/R",
  stateData: "#z~OPOStOS~OTPO~OUSO~OTVOXUOYUOZUO[UO]UO^YO_YO`YOaYOeWOmXO~Oc[OTVXrVXjVXkVX~O^]O~OnaO~OTbO~OicO~OjdOkfX~OkeO~O^fO~OjkOqlO~Oa`_mXYZ[]^TY~",
  goto: "!lqPPPruPP{!RPPPPPPPPP!RP!RP!V!Y!]PPP!RPP!c!fRROQQORTRQZSRicTYScR`WR_WQ^WRjdRhaQgaRmk",
  nodeNames: "⚠ Comment JSL TypedefList TypeDef Identifier ARROW TypeExpr Primitive Int Float Fak Bool UUID FAKLITERAL IntLiteral FloatLiteral BoolLiteral UnionExpr PIPE SchemaExpr L_BRACE InnerSchemaExpr KeyValList KeyVal COLON COMMA R_BRACE EnumExpr Enum L_PAREN EnumValuesList EnumValue R_PAREN",
  maxTerm: 36,
  skippedNodes: [0,1],
  repeatNodeCount: 0,
  tokenData: "3{~RoXY#SYZ#S]^#Spq#Srs#exy$Vyz$[|}$a}!O$f!P!Q$q!Q![%`![!]%y!c!g&O!g!h&^!h!w&O!w!x'|!x!}&O#R#S&O#T#U&O#U#V)l#V#Y&O#Y#Z+[#Z#]&O#]#^/O#^#g&O#g#h0Y#h#i2r#i#o&O#o#p3l#p#q3q#q#r3v~#XSt~XY#SYZ#S]^#Spq#S~#hR!c!}#q#R#S#q#T#o#q~#tSrs$Q!c!}#q#R#S#q#T#o#q~$VO^~~$[On~~$aOq~~$fOj~~$iP!`!a$l~$qOU~~$tP!P!Q$w~$|SP~OY$wZ;'S$w;'S;=`%Y<%lO$w~%]P;=`<%l$w~%eQ_~!O!P%k!Q![%`~%nP!Q![%q~%vP`~!Q![%q~&OOi~~&TRT~!c!}&O#R#S&O#T#o&O~&cTT~!c!}&O#R#S&O#T#b&O#b#c&r#c#o&O~&wTT~!c!}&O#R#S&O#T#i&O#i#j'W#j#o&O~']TT~!c!}&O#R#S&O#T#a&O#a#b'l#b#o&O~'sRm~T~!c!}&O#R#S&O#T#o&O~(RTT~!c!w&O!w!x(b!x!}&O#R#S&O#T#o&O~(gTT~!c!k&O!k!l(v!l!}&O#R#S&O#T#o&O~({TT~!c!f&O!f!g)[!g!}&O#R#S&O#T#o&O~)cR]~T~!c!}&O#R#S&O#T#o&O~)qTT~!c!}&O#R#S&O#T#c&O#c#d*Q#d#o&O~*VTT~!c!}&O#R#S&O#T#c&O#c#d*f#d#o&O~*kTT~!c!}&O#R#S&O#T#`&O#`#a*z#a#o&O~+RR[~T~!c!}&O#R#S&O#T#o&O~+aUT~!c!}&O#R#S&O#T#U+s#U#`&O#`#a-c#a#o&O~+xTT~!c!}&O#R#S&O#T#`&O#`#a,X#a#o&O~,^TT~!c!}&O#R#S&O#T#g&O#g#h,m#h#o&O~,rTT~!c!}&O#R#S&O#T#X&O#X#Y-R#Y#o&O~-YRa~T~!c!}&O#R#S&O#T#o&O~-hTT~!c!}&O#R#S&O#T#c&O#c#d-w#d#o&O~-|ST~!c!}&O#R#S&O#T#U.Y#U#o&O~._TT~!c!}&O#R#S&O#T#h&O#h#i.n#i#o&O~.uRY~T~!c!}&O#R#S&O#T#o&O~/TTT~!c!}&O#R#S&O#T#b&O#b#c/d#c#o&O~/iTT~!c!}&O#R#S&O#T#h&O#h#i/x#i#o&O~0PRX~T~!c!}&O#R#S&O#T#o&O~0_TT~!c!}&O#R#S&O#T#h&O#h#i0n#i#o&O~0sTT~!c!}&O#R#S&O#T#f&O#f#g1S#g#o&O~1XTT~!c!}&O#R#S&O#T#]&O#]#^1h#^#o&O~1mTT~!c!}&O#R#S&O#T#b&O#b#c1|#c#o&O~2RTT~!c!}&O#R#S&O#T#Z&O#Z#[2b#[#o&O~2iRZ~T~!c!}&O#R#S&O#T#o&O~2wTT~!c!}&O#R#S&O#T#f&O#f#g3W#g#o&O~3]TT~!c!}&O#R#S&O#T#i&O#i#j,m#j#o&O~3qOe~~3vOc~~3{Ok~",
  tokenizers: [0],
  topRules: {"JSL":[0,2]},
  tokenPrec: 121
})

