// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%dOYQPOOO_QPO'#C`OOQO'#C_'#C_QYQPOOOdQPO,58zOOQO,58y,58yOOQO'#Cd'#CdO!_QPO'#CcO!sQPO'#CpO!xQPO'#CxO!}QPO'#DOOOQO'#Cc'#CcOOQO1G.f1G.fO#SQPO,59YO#XQPO'#CtOOQO'#Cs'#CsO#^QPO'#CrO#fQPO,59[O#kQPO,59dOdQPO,59jOOQO1G.t1G.tOdQPO,59`O!sQPO,59_OOQO1G.v1G.vOOQO'#C|'#C|OOQO'#C{'#C{O#pQPO1G/OO#xQPO1G/UOOQO1G.z1G.zOOQO1G.y1G.yO#kQPO,59gOOQO7+$j7+$jOOQO7+$p7+$pOOQO1G/R1G/R",
  stateData: "$]~OPOSxOS~OTPO~OUSO~OTVOXUOYUOZUO[UO]UO^ZO_ZO`ZOaZOeWOmXOsYO~Oc]OTVXvVXuVXjVXkVX~O^^O~OnbO~OtcO~OTdO~OieO~OjfOkfX~OkgO~O^hO~OjnOqoO~OupO~Osa`_mXYZ[]^TY~",
  goto: "!rsPPPtwPP}!WPPPPPPPPP!WP!WP!]!`!cPPP!WPP!i!lP!WRROQQORTRQ[SQkcRleVZSceRaWR`WQ_WRmfRjbQibRqn",
  nodeNames: "⚠ Comment JSL TypedefList TypeDef Identifier ARROW TypeExpr Primitive Int Float Fak Bool UUID FAKLITERAL IntLiteral FloatLiteral BoolLiteral UnionExpr PIPE SchemaExpr L_BRACE InnerSchemaExpr KeyValList KeyVal COLON COMMA R_BRACE EnumExpr Enum L_PAREN EnumValuesList EnumValue R_PAREN ListExpr List L_BRACKET R_BRACKET",
  maxTerm: 40,
  skippedNodes: [0,1],
  repeatNodeCount: 0,
  tokenData: "6R~RsXY#`YZ#`]^#`pq#`rs#qxy$cyz$h|}$m}!O$r!P!Q$}!Q![%l![!]&V!c!g&[!g!h&j!h!w&[!w!x(Y!x!}&[!}#O)x#P#Q)}#R#S&[#T#U&[#U#V*S#V#Y&[#Y#Z+r#Z#]&[#]#^/f#^#`&[#`#a0p#a#g&[#g#h2`#h#i4x#i#o&[#o#p5r#p#q5w#q#r5|~#eSx~XY#`YZ#`]^#`pq#`~#tR!c!}#}#R#S#}#T#o#}~$QSrs$^!c!}#}#R#S#}#T#o#}~$cO^~~$hOn~~$mOq~~$rOj~~$uP!`!a$x~$}OU~~%QP!P!Q%T~%YSP~OY%TZ;'S%T;'S;=`%f<%lO%T~%iP;=`<%l%T~%qQ_~!O!P%w!Q![%l~%zP!Q![%}~&SP`~!Q![%}~&[Oi~~&aRT~!c!}&[#R#S&[#T#o&[~&oTT~!c!}&[#R#S&[#T#b&[#b#c'O#c#o&[~'TTT~!c!}&[#R#S&[#T#i&[#i#j'd#j#o&[~'iTT~!c!}&[#R#S&[#T#a&[#a#b'x#b#o&[~(PRm~T~!c!}&[#R#S&[#T#o&[~(_TT~!c!w&[!w!x(n!x!}&[#R#S&[#T#o&[~(sTT~!c!k&[!k!l)S!l!}&[#R#S&[#T#o&[~)XTT~!c!f&[!f!g)h!g!}&[#R#S&[#T#o&[~)oR]~T~!c!}&[#R#S&[#T#o&[~)}Ot~~*SOu~~*XTT~!c!}&[#R#S&[#T#c&[#c#d*h#d#o&[~*mTT~!c!}&[#R#S&[#T#c&[#c#d*|#d#o&[~+RTT~!c!}&[#R#S&[#T#`&[#`#a+b#a#o&[~+iR[~T~!c!}&[#R#S&[#T#o&[~+wUT~!c!}&[#R#S&[#T#U,Z#U#`&[#`#a-y#a#o&[~,`TT~!c!}&[#R#S&[#T#`&[#`#a,o#a#o&[~,tTT~!c!}&[#R#S&[#T#g&[#g#h-T#h#o&[~-YTT~!c!}&[#R#S&[#T#X&[#X#Y-i#Y#o&[~-pRa~T~!c!}&[#R#S&[#T#o&[~.OTT~!c!}&[#R#S&[#T#c&[#c#d._#d#o&[~.dST~!c!}&[#R#S&[#T#U.p#U#o&[~.uTT~!c!}&[#R#S&[#T#h&[#h#i/U#i#o&[~/]RY~T~!c!}&[#R#S&[#T#o&[~/kTT~!c!}&[#R#S&[#T#b&[#b#c/z#c#o&[~0PTT~!c!}&[#R#S&[#T#h&[#h#i0`#i#o&[~0gRX~T~!c!}&[#R#S&[#T#o&[~0uTT~!c!}&[#R#S&[#T#]&[#]#^1U#^#o&[~1ZTT~!c!}&[#R#S&[#T#g&[#g#h1j#h#o&[~1oTT~!c!}&[#R#S&[#T#h&[#h#i2O#i#o&[~2VRs~T~!c!}&[#R#S&[#T#o&[~2eTT~!c!}&[#R#S&[#T#h&[#h#i2t#i#o&[~2yTT~!c!}&[#R#S&[#T#f&[#f#g3Y#g#o&[~3_TT~!c!}&[#R#S&[#T#]&[#]#^3n#^#o&[~3sTT~!c!}&[#R#S&[#T#b&[#b#c4S#c#o&[~4XTT~!c!}&[#R#S&[#T#Z&[#Z#[4h#[#o&[~4oRZ~T~!c!}&[#R#S&[#T#o&[~4}TT~!c!}&[#R#S&[#T#f&[#f#g5^#g#o&[~5cTT~!c!}&[#R#S&[#T#i&[#i#j-T#j#o&[~5wOe~~5|Oc~~6ROk~",
  tokenizers: [0],
  topRules: {"JSL":[0,2]},
  tokenPrec: 137
})

